const configRaw = import.meta.env.VITE_CONFIG;
let parsed = {};

if (configRaw) {
  try {
    parsed = JSON.parse(configRaw);
  } catch (error) {
    console.error("Error parsing VITE_CONFIG environment variable:", error);
  }
}

export const env = {
  VITE_REACT_APIKEY: parsed.VITE_REACT_APIKEY,
  VITE_REACT_AUTHDOMAIN: parsed.VITE_REACT_AUTHDOMAIN,
  VITE_REACT_PROJECTID: parsed.VITE_REACT_PROJECTID,
  VITE_REACT_STORAGEBUCKET: parsed.VITE_REACT_STORAGEBUCKET,
  VITE_REACT_MESSAGINGSENDERID: parsed.VITE_REACT_MESSAGINGSENDERID,
  VITE_REACT_APPID: parsed.VITE_REACT_APPID,
  VITE_REACT_MEASUREMENTID: parsed.VITE_REACT_MEASUREMENTID,
  VITE_REACT_TENANT_NAME: parsed.VITE_REACT_TENANT_NAME,
  VITE_REACT_TENANT_ID: parsed.VITE_REACT_TENANT_ID,
  VITE_REACT_DATABASE_NAME: parsed.VITE_REACT_DATABASE_NAME,
  VITE_REACT_USERS_PHOTOS_DIRECTORY: parsed.VITE_REACT_USERS_PHOTOS_DIRECTORY,
  VITE_REACT_ASSETS_PHOTOS_DIRECTORY: parsed.VITE_REACT_ASSETS_PHOTOS_DIRECTORY,
  VITE_REACT_SECTORS_COLLECTIONNAME: parsed.VITE_REACT_SECTORS_COLLECTIONNAME,
  VITE_REACT_USERTYPES_COLLECTIONNAME: parsed.VITE_REACT_USERTYPES_COLLECTIONNAME,
  VITE_REACT_ASSETTYPES_COLLECTIONNAME: parsed.VITE_REACT_ASSETTYPES_COLLECTIONNAME,
  VITE_REACT_STORAGELOCATIONS_COLLECTIONNAME: parsed.VITE_REACT_STORAGELOCATIONS_COLLECTIONNAME,
  VITE_REACT_ASSETSTATUS_COLLECTIONNAME: parsed.VITE_REACT_ASSETSTATUS_COLLECTIONNAME,
  VITE_REACT_USAGETYPES_COLLECTIONNAME: parsed.VITE_REACT_USAGETYPES_COLLECTIONNAME,
  VITE_REACT_USERS_COLLECTIONNAME: parsed.VITE_REACT_USERS_COLLECTIONNAME,
  VITE_REACT_ASSETS_COLLECTIONNAME: parsed.VITE_REACT_ASSETS_COLLECTIONNAME,
  VITE_REACT_RECORDS_COLLECTIONNAME: parsed.VITE_REACT_RECORDS_COLLECTIONNAME,
  VITE_REACT_REQUESTS_COLLECTIONNAME: parsed.VITE_REACT_REQUESTS_COLLECTIONNAME,
  VITE_REACT_REQUESTSSTATUS_COLLECTIONNAME: parsed.VITE_REACT_REQUESTSSTATUS_COLLECTIONNAME,
  VITE_REACT_REQUESTSTYPES_COLLECTIONNAME: parsed.VITE_REACT_REQUESTSTYPES_COLLECTIONNAME,
};
